version: '3.8'
services:
  uploader:
    build: .
    environment:
      S3_ACCOUNT_ID: ${S3_ACCOUNT_ID}
      S3_BUCKET: ${S3_BUCKET}
      S3_KEY_ID: ${S3_KEY_ID}
      S3_SECRET: ${S3_SECRET}
      LOCAL_STORAGE_PATH: /files
      TELEGRAM_APITOKEN: ${TELEGRAM_APITOKEN}
      MYSQL_URL: mysql://root:1@tcp(mysql:3306)/converter
    ports:
      - "127.0.0.1:9000:3333"
    volumes:
      - data:/data
      - ./tmp/files:/files
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_ROOT_HOST: "%"
    ports:
      - "34291:3306"
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
volumes:
  data:
  mysqldata:
