version: '3.8'
services:
  converter:
    build: .
    environment:
      S3_ENDPOINT: https://d5378c6907f086901818a81bb0c8ce54.r2.cloudflarestorage.com
      S3_BUCKET: testme
      S3_ACCOUNT_ID: d5378c6907f086901818a81bb0c8ce54
      S3_KEY_ID: 5746d2a029b637f934f923f944d38704
      S3_SECRET: afab7fc6626626abb38013afe65e6b02caec92534c3593aca8611d2f175b73b0
      LOCAL_STORAGE_PATH: /data
      MYSQL_URL: mysql://root:1@tcp(mysql:3306)/converter
      #MYSQL_URL: mysql://root:1@mysql:3306/converter
    ports:
      - "127.0.0.1:9000:3333"
    volumes:
      - data:/data
      - ./tmp/files:/files
    depends_on:
      mysql:
        condition: service_healthy


  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_ROOT_HOST: "%"
    ports:
      - "34291:3306"
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
volumes:
  data:
  mysqldata:
